name: akvelon_flutter_share_plugin_example
description: Demonstrates how to use the akvelon_flutter_share_plugin plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  akvelon_flutter_share_plugin:
    path: ../

  cupertino_icons: ^0.1.3
  path_provider: ^1.6.10
  multi_image_picker: ^4.6.7
  image_picker: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true